### ISSUE TITLE
No se puede hacer click

### ISSUE THREAD

**Issue by franciscop** [GuilleAmutio/sos-valencia#5]
Hay una parte de la web donde no se puede hacer click porque el panel de abajo no se esconde bien:

<img width="645" alt="image" src="https://github.com/user-attachments/assets/465881f6-1445-4b6f-8dea-b0a21985d0d3">

**Comment by GuilleAmutio** [comment]
Deberia haberse resuelto ya. Podrias darme mas info de si sigue ocurriendo? muchas gracias de antemano

**Comment by franciscop** [comment]
Todo bien!
